### ISSUE TITLE
Problem with Season24

### ISSUE THREAD

**Issue by jasimancas** [seiya-dev/pokemon-tv#17]
Hi, first of all, thank you very much for all the content, great job, I've been following you for months, I just realized that in the Season 24 in Spanish (folder "es") does not appear the episode 41 and 42, is there a problem? In the PokemonTV website if it appears.

Thanks you!

**Comment by seiya-git** [comment]
Hi. Thanks! Because of region lock, it's not always updated properly. Added.
Please report if something else is missing
