### ISSUE TITLE
watch.pokemon.com shut down

### ISSUE THREAD

**Issue by trueauracoral** [seiya-dev/pokemon-tv#47]
Since, the pokemon TV website is shutting down how will it affect this project? This repo is the only archive I know of for the site also it has multiple languages which is pretty useful. Will the video links still work?

More info at: https://www.pokemon.com/us/pokemon-news/pokemon-tv-to-discontinue-in-march-2024

**Comment by seiya-git** [comment]
1. This repo contains only metadata from Pokémon TV, no images or videos
2. This repo will also be affected when they remove videos and images from their CDN

**Comment by OldGuy111** [comment]
They still didn't remove the thumbnails. Odd.

**Comment by seiya-git** [comment]
Not odd, those used in main site
