### ISSUE TITLE
account disabled

### ISSUE THREAD

**Issue by Kalletorssola** [seiya-dev/pokemon-tv#68]
hi. this is the only place for me to watch pokemon anime in finnish. But when i today (sixth of july) opened it and wanted to watch some pokemon, it just showed me some error message that told me that account is disabled. It would be cool if yoou could fix it.

**Comment by seiya-git** [comment]
Probably Pokémon company turned off their cdn account, so sadly we cannot get access to videos now

**Comment by seiya-git** [comment]
Videos still available by direct link, should work now
