### ISSUE TITLE
Inaccessible seasons and single episodes

### ISSUE THREAD

**Issue by coolkirby2000** [seiya-dev/pokemon-tv#74]
Looking through the database/us and /uk JSON links, I am unable to view or download any files from Seasons 2, 3, 4, 7, 8, 11, 12, 23, 24, or 25.

Also, S19E05 and E08 are missing as well. Is there a fix for any of this? Your site has been a great resource for the last few months, but it's a shame their server might be removing these files.

**Comment by seiya-git** [comment]
https://github.com/seiya-dev/pokemon-tv/issues/77
