### ISSUE TITLE
Issues on Pokemon tv app

### ISSUE THREAD

**Issue by Semih-93-B** [seiya-dev/pokemon-tv#77]
Hey
Can you please help. The Pokemon tv app is the only place i Can with it on danish but almost every episodes on every seasons says “server failed” :(

**Comment by Semih-93-B** [comment]
I meant the site you made ofcourse not the original Pokemon tv app :)

**Comment by seiya-git** [comment]
Link is https://poke-tv.vercel.app/
You probably use fake website

**Comment by Semih-93-B** [comment]
![IMG_8513](https://github.com/user-attachments/assets/69a74d38-cae6-4319-950c-6f3572980952)

thanks for Quick answer but thats the site im using, never had any issue before now.

**Comment by seiya-git** [comment]
Some videos not available at the moment, sorry

**Comment by Memenami** [comment]
Also it's not "some", not a single video I tried to play worked.

**Comment by Istiyaq123** [comment]
Almost all of the HD episodes have been removed from Limelight Networks/Edgio servers.

**Comment by seiya-git** [comment]
Probably all video links are dead now, but Pokémon TV has relaunched as a YouTube channel.

**Comment by seiya-git** [comment]
https://poke-tv.vercel.app/ 
Videos now from YouTube
